### BAJAJ-ALLIANZ

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
pin=pd.read_csv(r"pincode.csv")

In [4]:
pin.head()

CircleName      RegionName       DivisionName  \
0  Andhra Pradesh Circle  Kurnool Region  Hindupur Division   
1  Andhra Pradesh Circle  Kurnool Region  Hindupur Division   
2  Andhra Pradesh Circle  Kurnool Region  Hindupur Division   
3  Andhra Pradesh Circle  Kurnool Region  Hindupur Division   
4  Andhra Pradesh Circle  Kurnool Region  Hindupur Division   

            OfficeName  Pincode OfficeType  Delivery   District  \
0       Peddakotla B.O   515631         BO  Delivery  ANANTAPUR   
1       Pinnadhari B.O   515631         BO  Delivery  ANANTAPUR   
2  Yerraguntapalle B.O   515631         BO  Delivery  ANANTAPUR   
3  Obulareddipalli B.O   515581         BO  Delivery  ANANTAPUR   
4       Odulapalli B.O   515581         BO  Delivery  ANANTAPUR   

        StateName   Latitude  Longitude  
0  ANDHRA PRADESH    14.5689   77.85624  
1  ANDHRA PRADESH    14.5281  77.857014  
2  ANDHRA PRADESH  14.561111   77.85715  
3  ANDHRA PRADESH    14.2488    78.2588  
4  ANDHRA PRADESH   14.24555    78.2477

In [5]:
pin=pin[['Pincode','StateName']]

In [6]:
pin.head()

Pincode       StateName
0   515631  ANDHRA PRADESH
1   515631  ANDHRA PRADESH
2   515631  ANDHRA PRADESH
3   515581  ANDHRA PRADESH
4   515581  ANDHRA PRADESH

In [7]:
pin=pin.rename(columns={'Pincode':'PINCODE'})

In [8]:
pin.head()

PINCODE       StateName
0   515631  ANDHRA PRADESH
1   515631  ANDHRA PRADESH
2   515631  ANDHRA PRADESH
3   515581  ANDHRA PRADESH
4   515581  ANDHRA PRADESH

In [9]:
baj=pd.read_csv(r"BAJAJALLIANZ.csv")

In [10]:
baj.head()

ID   AGE         EDUCATION            OCC   PINCODE PROD_CATEGORY  \
0  9354  27.0      masters_plus   salaried_pvt  495001.0          trad   
1  7823  58.0     graduate_plus  salaried_govt  272001.0          ulip   
2  6170  52.0      masters_plus  salaried_govt  721101.0          trad   
3  9199  52.0  higher_secondary       business  712612.0          trad   
4  9981  34.0     graduate_plus   salaried_pvt  110085.0          ulip   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  
0               5                  High                   6         Mar-22  
1               4                Medium                   5         Dec-21  
2               5                  High                   5         Aug-21  
3               3                Medium                   2         Mar-22  
4               6             Very_high                   6         Mar-22

In [11]:
baj['AGE']=pd.to_numeric(baj['AGE'])
baj['PINCODE']=pd.to_numeric(baj['PINCODE'])

In [12]:
baj.rename(columns={'OCC':'OCCUPATION'},inplace=True)

In [13]:
baj.isna().sum()

ID                        0
AGE                      18
EDUCATION                 0
OCCUPATION                0
PINCODE                   2
PROD_CATEGORY             0
INCOME_SEGMENT            0
PROSPERITY_INDEX_BAND     0
QUALITY_SCORE_BAND        0
ISSUANCE_MONTH            0
dtype: int64

In [14]:
baj.shape

(4500, 10)

In [15]:
baj=baj.dropna(how='any',axis=0)

In [16]:
baj.isna().sum()

ID                       0
AGE                      0
EDUCATION                0
OCCUPATION               0
PINCODE                  0
PROD_CATEGORY            0
INCOME_SEGMENT           0
PROSPERITY_INDEX_BAND    0
QUALITY_SCORE_BAND       0
ISSUANCE_MONTH           0
dtype: int64

In [17]:
baj['AGE']=baj['AGE'].astype(int)
baj['PINCODE']=baj['PINCODE'].astype(int)

In [18]:
baj.head()

ID  AGE         EDUCATION     OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27      masters_plus   salaried_pvt   495001          trad   
1  7823   58     graduate_plus  salaried_govt   272001          ulip   
2  6170   52      masters_plus  salaried_govt   721101          trad   
3  9199   52  higher_secondary       business   712612          trad   
4  9981   34     graduate_plus   salaried_pvt   110085          ulip   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  
0               5                  High                   6         Mar-22  
1               4                Medium                   5         Dec-21  
2               5                  High                   5         Aug-21  
3               3                Medium                   2         Mar-22  
4               6             Very_high                   6         Mar-22

In [19]:
bajaj = pd.merge(baj, pin, on='PINCODE', how="left")

In [20]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6         Mar-22   
1               5                  High                   6         Mar-22   
2               5                  High                   6         Mar-22   
3               5                  High                   6         Mar-22   
4               5                  High                   6         Mar-22   

      StateName  
0  CHHATTISGARH  
1  CHHATTISGARH  
2  CHHATTISGARH  
3  CHHATTISGARH  
4  CHHATTISGARH

In [21]:
bajaj=bajaj.rename(columns={'StateName':'INDIAN_REGION'})

In [22]:
bajaj['INDIAN_REGION'].replace(['ANDHRA PRADESH','TELANGANA','PUDUCHERRY','TAMIL NADU','KARNATAKA','KERALA'],'South',inplace=True)#regex=True,inplace=True)
bajaj['INDIAN_REGION'].replace(['ARUNACHAL PRADESH','ODISHA','JHARKHAND','WEST BENGAL','BIHAR','ASSAM','MANIPUR','MEGHALAYA','MIZORAM','NAGALAND','SIKKIM','TRIPURA'],'East',inplace=True)#regex=True,)
bajaj['INDIAN_REGION'].replace(['GOA', 'GUJARAT', 'MAHARASHTRA', 'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU'],'West',inplace=True)#,regex=True)
bajaj['INDIAN_REGION'].replace(['JAMMU AND KASHMIR', 'HIMACHAL PRADESH', 'PUNJAB', 'UTTARAKHAND', 'HARYANA', 'DELHI', 'RAJASTHAN','UTTAR PRADESH', 'CHANDIGARH','LADAKH'],'North',inplace=True)#,regex=True)
bajaj['INDIAN_REGION'].replace(['CHHATTISGARH', 'MADHYA PRADESH'],'Central',inplace=True)#,regex=True)

In [23]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6         Mar-22   
1               5                  High                   6         Mar-22   
2               5                  High                   6         Mar-22   
3               5                  High                   6         Mar-22   
4               5                  High                   6         Mar-22   

  INDIAN_REGION  
0       Central  
1       Central  
2       Central  
3       Central  
4       Central

In [24]:
bajaj['INDIAN_REGION'].value_counts()

North      16059
East       14901
West        6234
Central     4759
South       4246
Name: INDIAN_REGION, dtype: int64

In [25]:
bajaj['ISSUANCE_MONTH'].head()

0    Mar-22
1    Mar-22
2    Mar-22
3    Mar-22
4    Mar-22
Name: ISSUANCE_MONTH, dtype: object

In [26]:
bajaj[['ISSUANCE_MONTH','ISSUANCE_YEAR']]=bajaj['ISSUANCE_MONTH'].str.split('-',expand=True)

In [27]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6            Mar   
1               5                  High                   6            Mar   
2               5                  High                   6            Mar   
3               5                  High                   6            Mar   
4               5                  High                   6            Mar   

  INDIAN_REGION ISSUANCE_YEAR  
0       Central            22  
1       Central            22  
2       Central            22  
3       Central            22  
4       Central            22

In [28]:
bajaj['ISSUANCE_YEAR'].value_counts()

21    29169
22    17084
Name: ISSUANCE_YEAR, dtype: int64

In [29]:
bajaj['ISSUANCE_YEAR']=bajaj['ISSUANCE_YEAR'].map({'21':2021,'22':2022})

In [30]:
bajaj['ISSUANCE_YEAR'].head()

0    2022
1    2022
2    2022
3    2022
4    2022
Name: ISSUANCE_YEAR, dtype: int64

In [31]:
bajaj['ISSUANCE_YEAR'].value_counts()

2021    29169
2022    17084
Name: ISSUANCE_YEAR, dtype: int64

In [32]:
bajaj['ISSUANCE_MONTH'].dtype

dtype('O')

In [33]:
bajaj['ISSUANCE_MONTH']=bajaj['ISSUANCE_MONTH'].map({'Jan':'01','Feb':'02','Mar':'03','Apr':'04','May':'05',
                                                 'Jun':'06','Jul':'07','Aug':'08',
                                                 'Sep':'09','Oct':'10','Nov':'11','Dec':'12'})

In [34]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6             03   
1               5                  High                   6             03   
2               5                  High                   6             03   
3               5                  High                   6             03   
4               5                  High                   6             03   

  INDIAN_REGION  ISSUANCE_YEAR  
0       Central           2022  
1       Central           2022  
2       Central           2022  
3       Central           2022  
4       Central           2022

In [35]:
bajaj['ISSUANCE_YEAR']=bajaj['ISSUANCE_YEAR'].astype(str)

In [36]:
cols=['ISSUANCE_MONTH','ISSUANCE_YEAR']
bajaj['ISSU_MONTH_YEAR']=bajaj[cols].apply(lambda row:'-'.join(row.values),axis=1)

In [37]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6             03   
1               5                  High                   6             03   
2               5                  High                   6             03   
3               5                  High                   6             03   
4               5                  High                   6             03   

  INDIAN_REGION ISSUANCE_YEAR ISSU_MONTH_YEAR  
0       Central          2022         03-2022  
1       Central          2022         03-2022  
2       Central          2022         03-2022  
3       Central          2022         03-2022  
4       Central          2022         03-2022

In [38]:
bajaj.ISSU_MONTH_YEAR=pd.to_datetime(bajaj.ISSU_MONTH_YEAR)
bajaj['QTR'] = pd.to_datetime(bajaj.ISSU_MONTH_YEAR).dt.quarter

In [39]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND ISSUANCE_MONTH  \
0               5                  High                   6             03   
1               5                  High                   6             03   
2               5                  High                   6             03   
3               5                  High                   6             03   
4               5                  High                   6             03   

  INDIAN_REGION ISSUANCE_YEAR ISSU_MONTH_YEAR  QTR  
0       Central          2022      2022-03-01    1  
1       Central          2022      2022-03-01    1  
2       Central          2022      2022-03-01    1  
3       Central          2022      2022-03-01    1  
4       Central          2022      2022-03-01    1

In [40]:
cols=['ISSUANCE_MONTH','ISSU_MONTH_YEAR']
bajaj.drop(cols,axis=1,inplace=True)

In [41]:
bajaj.head()

ID  AGE     EDUCATION    OCCUPATION  PINCODE PROD_CATEGORY  \
0  9354   27  masters_plus  salaried_pvt   495001          trad   
1  9354   27  masters_plus  salaried_pvt   495001          trad   
2  9354   27  masters_plus  salaried_pvt   495001          trad   
3  9354   27  masters_plus  salaried_pvt   495001          trad   
4  9354   27  masters_plus  salaried_pvt   495001          trad   

   INCOME_SEGMENT PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND INDIAN_REGION  \
0               5                  High                   6       Central   
1               5                  High                   6       Central   
2               5                  High                   6       Central   
3               5                  High                   6       Central   
4               5                  High                   6       Central   

  ISSUANCE_YEAR  QTR  
0          2022    1  
1          2022    1  
2          2022    1  
3          2022    1  
4          2022    1

In [42]:
bajaj=bajaj.drop(['ID','PINCODE'],axis=1)

In [43]:
bajaj['EDUCATION'].value_counts()

graduate_plus        25749
matriculation         7258
higher_secondary      4612
missing               3480
masters_plus          3085
non_matriculation     2069
Name: EDUCATION, dtype: int64

In [44]:
(((bajaj['EDUCATION']=='missing').sum())/len(bajaj))*100

7.523836291699998

In [45]:
bajaj.drop(bajaj[bajaj['EDUCATION'] =='missing'].index, inplace = True)

In [46]:
bajaj['EDUCATION']=bajaj['EDUCATION'].astype(str)

In [47]:
bajaj['EDUCATION'].head()

0    masters_plus
1    masters_plus
2    masters_plus
3    masters_plus
4    masters_plus
Name: EDUCATION, dtype: object

In [48]:
bajaj['OCCUPATION'].value_counts()

business         21528
salaried_pvt      8874
agriculture       4977
salaried_govt     4057
professional      2089
retired            588
housewife          536
missing             88
student             34
salaried             2
Name: OCCUPATION, dtype: int64

In [49]:
(((bajaj['OCCUPATION']=='missing').sum())/len(bajaj))*100

0.20573726416197136

In [50]:
bajaj.drop(bajaj[bajaj['OCCUPATION'] =='missing'].index, inplace = True)

In [51]:
bajaj['OCCUPATION']=bajaj['OCCUPATION'].astype(str)

In [52]:
bajaj['OCCUPATION'].head()

0    salaried_pvt
1    salaried_pvt
2    salaried_pvt
3    salaried_pvt
4    salaried_pvt
Name: OCCUPATION, dtype: object

In [53]:
bajaj['PROD_CATEGORY'].value_counts()

trad    29565
ulip     9707
term     3413
Name: PROD_CATEGORY, dtype: int64

In [54]:
bajaj['INCOME_SEGMENT'].value_counts()

 3     12256
 2      8605
 4      8381
 5      5426
 1      2889
 6      2606
 7      1572
 8       490
 9       349
-99       61
 10       50
Name: INCOME_SEGMENT, dtype: int64

In [55]:
bajaj.drop(bajaj[bajaj['INCOME_SEGMENT'] ==-99].index, inplace = True)

In [56]:
bajaj['INCOME_SEGMENT'].head()

0    5
1    5
2    5
3    5
4    5
Name: INCOME_SEGMENT, dtype: int64

In [57]:
bajaj['PROSPERITY_INDEX_BAND'].value_counts()

Medium       19937
High         12886
Very_high     3825
Very_low      2716
Low           2533
Missing        727
Name: PROSPERITY_INDEX_BAND, dtype: int64

In [58]:
(((bajaj['PROSPERITY_INDEX_BAND']=='Missing').sum())/len(bajaj))*100

1.705611861861862

In [59]:
bajaj.drop(bajaj[bajaj['PROSPERITY_INDEX_BAND'] =='Missing'].index, inplace = True)

In [60]:
bajaj['PROSPERITY_INDEX_BAND']=bajaj['PROSPERITY_INDEX_BAND'].astype(str)

In [61]:
bajaj['PROSPERITY_INDEX_BAND'].head()

0    High
1    High
2    High
3    High
4    High
Name: PROSPERITY_INDEX_BAND, dtype: object

In [62]:
bajaj['QUALITY_SCORE_BAND'].value_counts()

4    14945
5    10899
3     7847
2     6360
6     1703
1      143
Name: QUALITY_SCORE_BAND, dtype: int64

In [63]:
bajaj['QUALITY_SCORE_BAND'].head()

0    6
1    6
2    6
3    6
4    6
Name: QUALITY_SCORE_BAND, dtype: int64

In [64]:
bajaj['QTR']=bajaj['QTR'].astype(str)

In [65]:
bajaj['QTR']=bajaj['QTR'].map({'1':'Q1','2':'Q2','3':'Q3','4':'Q4'})

In [66]:
bajaj.dtypes

AGE                       int32
EDUCATION                object
OCCUPATION               object
PROD_CATEGORY            object
INCOME_SEGMENT            int64
PROSPERITY_INDEX_BAND    object
QUALITY_SCORE_BAND        int64
INDIAN_REGION            object
ISSUANCE_YEAR            object
QTR                      object
dtype: object

In [67]:
bajaj.isna().any().sum()

1

In [68]:
bajaj.isnull().values.any()

True

In [69]:
bajaj.head()

AGE     EDUCATION    OCCUPATION PROD_CATEGORY  INCOME_SEGMENT  \
0   27  masters_plus  salaried_pvt          trad               5   
1   27  masters_plus  salaried_pvt          trad               5   
2   27  masters_plus  salaried_pvt          trad               5   
3   27  masters_plus  salaried_pvt          trad               5   
4   27  masters_plus  salaried_pvt          trad               5   

  PROSPERITY_INDEX_BAND  QUALITY_SCORE_BAND INDIAN_REGION ISSUANCE_YEAR QTR  
0                  High                   6       Central          2022  Q1  
1                  High                   6       Central          2022  Q1  
2                  High                   6       Central          2022  Q1  
3                  High                   6       Central          2022  Q1  
4                  High                   6       Central          2022  Q1

### Feature Extraction

#### Dummy Variables

In [70]:
cols=['EDUCATION','OCCUPATION','QUALITY_SCORE_BAND','INCOME_SEGMENT','INDIAN_REGION','PROSPERITY_INDEX_BAND','ISSUANCE_YEAR','QTR']
baj_dum=bajaj[cols]

In [71]:
baj_dum.columns

Index(['EDUCATION', 'OCCUPATION', 'QUALITY_SCORE_BAND', 'INCOME_SEGMENT',
       'INDIAN_REGION', 'PROSPERITY_INDEX_BAND', 'ISSUANCE_YEAR', 'QTR'],
      dtype='object')

In [72]:
baj_dum=pd.get_dummies(data=baj_dum,columns=baj_dum.columns,
                       prefix=['EDUCATION', 'OCCUPATION', 'QUALITY_SCORE_BAND','INCOME_SEGMENT','INDIAN_REGION',
                               'PROSPERITY_INDEX_BAND', 'ISSUANCE_YEAR', 'QTR'],
                       dummy_na=False,drop_first=True)

In [73]:
baj_dum.shape

(41897, 38)

In [74]:
cols=['EDUCATION','OCCUPATION','QUALITY_SCORE_BAND','INCOME_SEGMENT','INDIAN_REGION',
      'PROSPERITY_INDEX_BAND','ISSUANCE_YEAR','QTR']
bajaj=bajaj.drop(cols,axis=1)

In [75]:
bajaj_fin=pd.concat([bajaj,baj_dum],axis=1)

In [76]:
bajaj_fin.columns

Index(['AGE', 'PROD_CATEGORY', 'EDUCATION_higher_secondary',
       'EDUCATION_masters_plus', 'EDUCATION_matriculation',
       'EDUCATION_non_matriculation', 'OCCUPATION_business',
       'OCCUPATION_housewife', 'OCCUPATION_professional', 'OCCUPATION_retired',
       'OCCUPATION_salaried', 'OCCUPATION_salaried_govt',
       'OCCUPATION_salaried_pvt', 'OCCUPATION_student', 'QUALITY_SCORE_BAND_2',
       'QUALITY_SCORE_BAND_3', 'QUALITY_SCORE_BAND_4', 'QUALITY_SCORE_BAND_5',
       'QUALITY_SCORE_BAND_6', 'INCOME_SEGMENT_2', 'INCOME_SEGMENT_3',
       'INCOME_SEGMENT_4', 'INCOME_SEGMENT_5', 'INCOME_SEGMENT_6',
       'INCOME_SEGMENT_7', 'INCOME_SEGMENT_8', 'INCOME_SEGMENT_9',
       'INCOME_SEGMENT_10', 'INDIAN_REGION_East', 'INDIAN_REGION_North',
       'INDIAN_REGION_South', 'INDIAN_REGION_West',
       'PROSPERITY_INDEX_BAND_Low', 'PROSPERITY_INDEX_BAND_Medium',
       'PROSPERITY_INDEX_BAND_Very_high', 'PROSPERITY_INDEX_BAND_Very_low',
       'ISSUANCE_YEAR_2022', 'QTR_Q2', 'QTR_Q3'

In [77]:
bajaj_fin.shape

(41897, 40)

### Feature Selection

In [78]:
#Creating the dependent variable class
factor = pd.factorize(bajaj_fin['PROD_CATEGORY'])
bajaj_fin.PROD_CATEGORY = factor[0]
definitions = factor[1]
print(bajaj_fin.PROD_CATEGORY.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: PROD_CATEGORY, dtype: int64
Index(['trad', 'ulip', 'term'], dtype='object')


In [79]:
y=bajaj_fin['PROD_CATEGORY']
X=bajaj_fin.drop(['PROD_CATEGORY'],axis=1)

### Train-Test-Split

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [82]:
X_train.head()

AGE  EDUCATION_higher_secondary  EDUCATION_masters_plus  \
28385   49                           0                       0   
712     34                           0                       0   
34766   41                           0                       0   
33272   24                           0                       0   
35756   45                           0                       0   

       EDUCATION_matriculation  EDUCATION_non_matriculation  \
28385                        0                            0   
712                          0                            0   
34766                        0                            0   
33272                        0                            0   
35756                        0                            0   

       OCCUPATION_business  OCCUPATION_housewife  OCCUPATION_professional  \
28385                    0                     0                        0   
712                      1                     0                        0   
34766                    0                     1                        0   
33272                    1                     0                        0   
35756                    0                     0                        0   

       OCCUPATION_retired  OCCUPATION_salaried  ...  INDIAN_REGION_South  \
28385                   0                    0  ...                    0   
712                     0                    0  ...                    0   
34766                   0                    0  ...                    0   
33272                   0                    0  ...                    1   
35756                   0                    0  ...                    0   

       INDIAN_REGION_West  PROSPERITY_INDEX_BAND_Low  \
28385                   1                          0   
712                     0                          0   
34766                   0                          0   
33272                   0                          0   
35756                   0                          0   

       PROSPERITY_INDEX_BAND_Medium  PROSPERITY_INDEX_BAND_Very_high  \
28385                             1                                0   
712                               1                                0   
34766                             1                                0   
33272                             0                                0   
35756                             0                                1   

       PROSPERITY_INDEX_BAND_Very_low  ISSUANCE_YEAR_2022  QTR_Q2  QTR_Q3  \
28385                               0                   0       0       0   
712                                 0                   0       0       1   
34766                               0                   0       1       0   
33272                               0                   1       0       0   
35756                               0                   0       0       1   

       QTR_Q4  
28385       1  
712         0  
34766       0  
33272       0  
35756       0  

[5 rows x 39 columns]

In [83]:
y_train.head()

28385    1
712      0
34766    0
33272    0
35756    2
Name: PROD_CATEGORY, dtype: int64

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
from sklearn.linear_model import LogisticRegression

In [86]:
#importing the necessary libraries 
from sklearn.feature_selection import RFE  
rfe = RFE(RandomForestClassifier(),n_features_to_select=10)

In [87]:
_=rfe.fit(X_train,y_train)

In [88]:
X_train=X_train.loc[:,rfe.support_]
X_test=X_test.loc[:,rfe.support_]

In [89]:
X_train.head()

AGE  OCCUPATION_business  QUALITY_SCORE_BAND_5  INCOME_SEGMENT_3  \
28385   49                    0                     0                 0   
712     34                    1                     0                 1   
34766   41                    0                     0                 0   
33272   24                    1                     0                 0   
35756   45                    0                     0                 0   

       INCOME_SEGMENT_5  INDIAN_REGION_East  INDIAN_REGION_North  \
28385                 0                   0                    0   
712                   0                   0                    1   
34766                 0                   0                    1   
33272                 0                   0                    0   
35756                 1                   0                    1   

       PROSPERITY_INDEX_BAND_Medium  ISSUANCE_YEAR_2022  QTR_Q4  
28385                             1                   0       1  
712                               1                   0       0  
34766                             1                   0       0  
33272                             0                   1       0  
35756                             0                   0       0

In [90]:
print(rfe.ranking_)

[ 1 16  7 12 24  1 26 19 22 30 13  4 29 21 15  5  1 23  8  1  2  1 11 17
 27 25 28  1  1 14  6 18  1 10 20  1  9  3  1]


In [91]:
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
print(n_estimators)

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]


In [92]:
from sklearn.model_selection import RandomizedSearchCV

In [93]:
# #Randomized Search CV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]

# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

In [94]:
# # Create the random grid

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

{'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 10, 15, 20, 25, 30], 'min_samples_split': [2, 5, 10, 15, 100], 'min_samples_leaf': [1, 2, 5, 10]}


In [95]:
rfc_classifier=RandomForestClassifier(criterion = 'entropy', random_state = 42)

In [96]:
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations

rfc = RandomizedSearchCV(estimator = rfc_classifier, param_distributions = random_grid,
                                scoring='neg_mean_squared_error', n_iter = 10, cv = 5,
                                verbose=2, random_state=42, n_jobs = 1)

In [97]:
rfc.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   8.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   8.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   8.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   8.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   8.6s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=  12.9s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=  12.8s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimator

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(criterion='entropy',
                                                    random_state=42),
                   n_jobs=1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=2)

In [98]:
rfc.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 25}

In [99]:
rfc_best = RandomForestClassifier(n_estimators=1000,min_samples_split=2,min_samples_leaf= 1,
                             max_features= 'sqrt',max_depth= 25)

In [100]:
rfc.best_score_

-0.16592213890848442

In [102]:
rfc_best.fit(X_train,y_train)

RandomForestClassifier(max_depth=25, max_features='sqrt', n_estimators=1000)

In [103]:
# Predicting the Test set results
y_pred_rfc = rfc_best.predict(X_test)

In [104]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,y_pred_rfc))

[[8190  344   92]
 [ 441 2414   38]
 [ 223   52  776]]


In [105]:
from sklearn.metrics import accuracy_score

rfc_accuracy=accuracy_score(y_test,y_pred_rfc)

In [106]:
rfc_accuracy=round(rfc_accuracy*100,2)

In [107]:
print(rfc_accuracy)

90.53


#### Logistic Regression

In [108]:
y_train.shape

(29327,)

In [109]:
X_train.shape

(29327, 10)

In [110]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
lr = LogisticRegression()

In [111]:
lr.fit(X_train,y_train)

LogisticRegression()

In [112]:
y_pred_lr=lr.predict(X_test)

In [113]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [114]:
confusion_matrix(y_test,y_pred_lr)

array([[8341,  203,   82],
       [2482,  369,   42],
       [ 880,   38,  133]], dtype=int64)

In [115]:
precision_score(y_test, y_pred_lr,average='micro')

0.7035003977724742

In [116]:
recall_score(y_test, y_pred_lr,average='micro')

0.7035003977724742

In [117]:
f1_score(y_test, y_pred_lr,average='micro')

0.7035003977724742

In [118]:
lr_accuracy=accuracy_score(y_test,y_pred_lr)

In [119]:
lr_accuracy=round(lr_accuracy*100,2)

In [120]:
print(lr_accuracy)

70.35


### Decision Tree

In [121]:
from sklearn.tree import DecisionTreeClassifier

dtc=DecisionTreeClassifier()

In [122]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [123]:
y_pred_dtc=dtc.predict(X_test)

In [124]:
print(confusion_matrix(y_test,y_pred_dtc))

[[8227  312   87]
 [ 456 2400   37]
 [ 228   51  772]]


In [125]:
dtc_accuracy=accuracy_score(y_test,y_pred_dtc)

In [126]:
dtc_accuracy=round(dtc_accuracy*100,2)

In [127]:
print(dtc_accuracy)

90.68


### K Nearest Neighbour

In [128]:
from sklearn.neighbors import KNeighborsClassifier

In [129]:
knn=KNeighborsClassifier()

In [130]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [131]:
y_pred_knn=knn.predict(X_test)

In [132]:
print(confusion_matrix(y_test,y_pred_knn))

[[8197  336   93]
 [ 595 2261   37]
 [ 269   46  736]]


In [133]:
knn_accuracy=accuracy_score(y_test,y_pred_knn)

In [134]:
knn_accuracy=round(knn_accuracy*100,2)

In [135]:
print(knn_accuracy)

89.05


### Adaboost Classifier

In [136]:
from sklearn.ensemble import AdaBoostClassifier

In [137]:
abc=AdaBoostClassifier()

In [138]:
abc.fit(X_train,y_train)

AdaBoostClassifier()

In [139]:
y_pred_abc=abc.predict(X_test)

In [140]:
print(confusion_matrix(y_test,y_pred_abc))

[[8279  177  170]
 [2303  486  104]
 [ 847   26  178]]


In [141]:
adaboost_accuracy=accuracy_score(y_test,y_pred_abc)

In [142]:
adaboost_accuracy=round(adaboost_accuracy*100,2)

In [143]:
print(adaboost_accuracy)

71.15


### Naive Bayes

In [144]:
from sklearn.naive_bayes import GaussianNB

In [145]:
gnb=GaussianNB()

In [146]:
gnb.fit(X_train,y_train)

GaussianNB()

In [147]:
y_pred_gnb=gnb.predict(X_test)

In [148]:
print(confusion_matrix(y_test,y_pred_gnb))

[[7035  719  872]
 [1640  764  489]
 [ 441   61  549]]


In [149]:
gnb_accuracy=accuracy_score(y_test,y_pred_gnb)

In [150]:
gnb_accuracy=round(gnb_accuracy*100,2)

In [151]:
print(gnb_accuracy)

66.41


### XGBoost Classifier

In [152]:
import xgboost as xgb

In [153]:
xgbc=xgb.XGBClassifier()

In [154]:
xgbc.fit(X_train,y_train)

[23:12:38] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [155]:
y_pred_xgbc=xgbc.predict(X_test)

In [156]:
print(confusion_matrix(y_test,y_pred_xgbc))

[[8251  269  106]
 [ 879 1959   55]
 [ 315   46  690]]


In [157]:
xgbc_accuracy=accuracy_score(y_test,y_pred_xgbc)

In [158]:
xgbc_accuracy=round(xgbc_accuracy*100,2)

In [159]:
print(xgbc_accuracy)

86.71


### Model Finalising and Pickling

In [160]:
ultimate_classifer={xgb:'xgbc_model',gnb:'gnb_model',abc:'adaboost_model',
                knn:'knn_model',dtc:'dtc_model',lr:'Logistic_model',
                rfc_best:'rfc_model'}

In [161]:
ultimate_model={'xgbc_model':xgbc_accuracy,'gnb_model':gnb_accuracy,'adaboost_model':adaboost_accuracy,
                'knn_model':knn_accuracy,'dtc_model':dtc_accuracy,'Logistic_model':lr_accuracy,
                'rfc_model':rfc_accuracy}

In [162]:
keymax=max(zip(ultimate_model.values(),ultimate_model.keys()))[1]

In [163]:
keymax

'dtc_model'

In [164]:
print(list(ultimate_classifer.keys())[list(ultimate_classifer.values()).index(keymax)])

DecisionTreeClassifier()


In [165]:
final_model=list(ultimate_classifer.keys())[list(ultimate_classifer.values()).index(keymax)]

In [166]:
final_model

DecisionTreeClassifier()

In [167]:
# Here Decision tree is best algorithm to produce best accuracy

In [168]:
reversefactor = dict(zip(range(3),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred_dtc = np.vectorize(reversefactor.get)(y_pred_dtc)

In [169]:
final_df=pd.DataFrame({'PROD_CATEGORY':y_test,'PRED_PROD_CATEGORY':y_pred_dtc})

In [170]:
final_df.head()

PROD_CATEGORY PRED_PROD_CATEGORY
0          ulip               ulip
1          trad               trad
2          trad               trad
3          ulip               ulip
4          ulip               ulip

In [171]:
final_df=final_df.reset_index()

In [172]:
final_df.head()

index PROD_CATEGORY PRED_PROD_CATEGORY
0      0          ulip               ulip
1      1          trad               trad
2      2          trad               trad
3      3          ulip               ulip
4      4          ulip               ulip

In [173]:
final_df=final_df[['index','PRED_PROD_CATEGORY']]

In [174]:
final_df=final_df.rename({'index':'ID'},axis=1)

In [175]:
final_df.head()

ID PRED_PROD_CATEGORY
0   0               ulip
1   1               trad
2   2               trad
3   3               ulip
4   4               ulip

### Saving the Model

In [176]:
import pickle

#dump information to that file
pickle.dump(final_model,open('model.pkl','wb'))

#load a model
pickle.load(open('model.pkl','rb'))

DecisionTreeClassifier()

In [177]:
final_df.to_csv('Baja_Allianz-submission.csv',index=False)